# Base compose files for:

version: '2'  # v3 does not support 'extends' yet

services:

  peer0.ipdc.ipdc.com:
    extends:
      file: ./peer-base.yaml
      service: peer-base
    container_name: peer0.ipdc.ipdc.com
    hostname: peer0.ipdc.ipdc.com
    environment:
      - CORE_PEER_ID=peer0.ipdc.ipdc.com
      - CORE_PEER_ADDRESS=peer0.ipdc.ipdc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ipdc.ipdc.com:7051      
      - CORE_PEER_LISTENADDRESS=peer0.ipdc.ipdc.com:7051      
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.ipdc.ipdc.com:7052
      - CORE_PEER_EVENTS_ADDRESS=peer0.ipdc.ipdc.com:7051      
      - CORE_PEER_LOCALMSPID=IpdcMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password 
    volumes:
        - ./crypto-config/peerOrganizations/ipdc.ipdc.com/peers/peer0.ipdc.ipdc.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/ipdc.ipdc.com/peers/peer0.ipdc.ipdc.com/tls:/etc/hyperledger/fabric/tls

    network_mode: "host"
    ports: 
      - 7051:7051 
      - 7053:7053 
    restart: always    
    command: peer node start    
